### ISSUE TITLE
NameError: name 'browser' is not defined

### ISSUE THREAD

**Issue by ChunQiu2076** [tuoluo348/zhsQA#1]
运行auto_qa之后，报错
  File "e:\wkJB\hudong\zhsQA-main\auto_qa.py", line 191, in <module>
    browser.quit()
NameError: name 'browser' is not defined
上面是报错信息，当我把browser.quit()注释掉之后，有进度条的显示，但是实际上并没有提问和评论什么的

**Comment by tuoluo348** [comment]
尝试安装火狐浏览器和火狐浏览器驱动
驱动下载地址
https://github.com/mozilla/geckodriver/releases

**Comment by tuoluo348** [comment]
> 试用安装火狐浏览器和火狐浏览器驱动
> 驱动下载地址
> https://github.com/mozilla/geckodriver/releases

**Comment by tuoluo348** [comment]
> 运行auto_qa之后，报错 File "e:\wkJB\hudong\zhsQA-main\auto_qa.py", line 191, in browser.quit() NameError: name 'browser' is not defined 上面是报错信息，当我把browser.quit()注释掉之后，有进度条的显示，但是实际上并没有提问和评论什么的

**Comment by tuoluo348** [comment]
> 运行auto_qa之后，报错 File "e:\wkJB\hudong\zhsQA-main\auto_qa.py", line 191, in browser.quit() NameError: name 'browser' is not defined 上面是报错信息，当我把browser .quit() 评论掉了之后，有条条的显示，但实际上并没有提出意见和评论什么的

试用安装火狐浏览器和火狐浏览器驱动
驱动下载地址
https://github.com/mozilla/geckodriver/releases

**Comment by ChunQiu2076** [comment]
驱动安装好之后，确实可以启动火狐，可以登录，手动过滑块，但是进入到我的学堂之后，就闪退了
